const animeData = [
    {
        id: 1,
        name: "Naruto Shippuden",
        image: "images/naruto.png",
        rating: 8.7,
        genres: ["Ação", "Shounen", "Aventura"],
        description: "Naruto Uzumaki quer se tornar o maior ninja da vila.",
        fullDescription: "Naruto Shippuden é a continuação da série original Naruto e segue o jovem ninja Naruto Uzumaki em sua jornada para se tornar o Hokage, o líder de sua vila, e ganhar o respeito de seus colegas.",
        episodes: 500,
        seasons: 21,
        trailer: "https://www.youtube.com/embed/1y_Xp26p0Sg"
    },
    {
        id: 2,
        name: "One Piece",
        image: "https://media.kitsu.app/anime/poster_images/12/large.jpg",
        rating: 8.9,
        genres: ["Ação", "Shounen", "Aventura"],
        description: "Luffy e sua tripulação buscam o tesouro supremo.",
        fullDescription: "Monkey D. Luffy recusa-se a deixar que qualquer coisa o impeça de se tornar o rei de todos os piratas. Com um curso traçado para as águas traiçoeiras da Grand Line, este é um capitão que nunca desistirá até que tenha conseguido o maior tesouro da Terra: o lendário One Piece!",
        episodes: 1100,
        seasons: 20,
        trailer: "https://www.youtube.com/embed/S8_YwFLCh4U"
    },
    {
        id: 3,
        name: "Attack on Titan",
        image: "https://media.kitsu.app/anime/poster_images/7442/large.jpg",
        rating: 9.1,
        genres: ["Ação", "Drama", "Terror", "Shounen"],
        description: "A humanidade luta contra gigantes comedores de gente.",
        fullDescription: "Depois que sua cidade natal é destruída e sua mãe é morta, o jovem Eren Jaeger jura limpar a terra dos gigantes Titãs humanóides que levaram a humanidade à beira da extinção.",
        episodes: 88,
        seasons: 4,
        trailer: "https://www.youtube.com/embed/MGRm4IzK1SQ"
    },
    {
        id: 4,
        name: "Death Note",
        image: "https://media.kitsu.app/anime/poster_images/1376/large.jpg",
        rating: 9.0,
        genres: ["Mistério", "Thriller", "Drama", "Psicológico"],
        description: "Um caderno que mata quem tem seu nome escrito.",
        fullDescription: "Um estudante de ensino médio inteligente descobre um caderno capaz de matar qualquer pessoa cujo nome seja escrito nele. Ele decide usar o caderno para limpar o mundo do mal.",
        episodes: 37,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/NlJZ-YgAt-c"
    },
    {
        id: 5,
        name: "Demon Slayer",
        image: "https://media.kitsu.app/anime/poster_images/41370/large.jpg",
        rating: 8.7,
        genres: ["Ação", "Shounen", "Sobrenatural"],
        description: "Tanjiro luta contra demônios para salvar sua irmã.",
        fullDescription: "Um jovem se torna um caçador de demônios depois que sua família é massacrada e sua irmã mais nova é transformada em um demônio.",
        episodes: 55,
        seasons: 4,
        trailer: "https://www.youtube.com/embed/VQGCKyvzIM4"
    },
    {
        id: 6,
        name: "Jujutsu Kaisen",
        image: "https://media.kitsu.app/anime/42765/poster_image/large-5ce19551c1a6cf995b378205b9149b5c.jpeg",
        rating: 8.6,
        genres: ["Ação", "Shounen", "Sobrenatural"],
        description: "Yuji Itadori entra no mundo das maldições.",
        fullDescription: "Um estudante do ensino médio se junta a uma organização secreta de feiticeiros para combater maldições poderosas que assolam a humanidade.",
        episodes: 47,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/hB2S_9A_Nms"
    },
    {
        id: 7,
        name: "Solo Leveling",
        image: "https://media.kitsu.app/anime/46231/poster_image/large-cdadff31f42490b9f48a035939a01a92.jpeg",
        rating: 8.5,
        genres: ["Ação", "Isekai", "Fantasia"],
        description: "O caçador mais fraco se torna o mais forte.",
        fullDescription: "Em um mundo onde caçadores lutam contra monstros em masmorras, Sung Jin-woo é o caçador mais fraco de todos, até que uma missão misteriosa lhe dá o poder de subir de nível sozinho.",
        episodes: 12,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/uG67UByv2pY"
    },
    {
        id: 8,
        name: "Chainsaw Man",
        image: "https://media.kitsu.app/anime/43806/poster_image/large-815d6008fb3b56f4291b9f0ffa05cd8f.jpeg",
        rating: 8.5,
        genres: ["Ação", "Terror", "Shounen"],
        description: "Denji se funde com seu cão demônio serra elétrica.",
        fullDescription: "Denji é um jovem pobre que trabalha como caçador de demônios para pagar as dívidas de seu pai falecido. Após ser traído, ele se funde with seu cão demônio, Pochita, tornando-se o Homem-Motosserra.",
        episodes: 12,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/l96zmDlWCBk"
    },
    {
        id: 9,
        name: "Blue Lock",
        image: "https://media.kitsu.app/anime/44973/poster_image/large-ca235304c71f4233e60f6efb3967654d.jpeg",
        rating: 8.2,
        genres: ["Esporte", "Drama", "Shounen", "Escolar"],
        description: "A busca pelo atacante egoísta definitivo do Japão.",
        fullDescription: "Após a eliminação do Japão na Copa do Mundo de 2018, a federação de futebol japonesa cria o projeto Blue Lock: um centro de treinamento rigoroso para criar o melhor atacante do mundo.",
        episodes: 24,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/U9u0_u3oYI8"
    },
    {
        id: 10,
        name: "Tokyo Revengers",
        image: "https://media.kitsu.app/anime/poster_images/43321/large.jpg",
        rating: 8.0,
        genres: ["Ação", "Drama", "Shounen", "Escolar"],
        description: "Takemichi viaja no tempo para salvar sua ex-namorada.",
        fullDescription: "Takemichi Hanagaki descobre que sua ex-namorada foi morta pela Gangue Tokyo Manji. Ele acidentalmente viaja no tempo para o passado e decide mudar o futuro para salvá-la.",
        episodes: 50,
        seasons: 3,
        trailer: "https://www.youtube.com/embed/r9Sj7YkF_gE"
    },
    {
        id: 11,
        name: "Spy x Family",
        image: "https://media.kitsu.app/anime/45398/poster_image/large-c26c1e0b77e881fcd66475af6bd22c57.jpeg",
        rating: 8.4,
        genres: ["Comédia", "Drama", "Shounen"],
        description: "Um espião, uma assassina e uma telepata fingem ser uma família.",
        fullDescription: "Um espião deve 'construir uma família' para executar uma missão, sem perceber que a garota que ele adota como filha é uma telepata, e a mulher com quem ele concorda em se casar é uma assassina habilidosa.",
        episodes: 37,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/O7zJ_0fH_5c"
    },
    {
        id: 12,
        name: "Your Name",
        image: "https://media.kitsu.app/anime/poster_images/11614/large.jpg",
        rating: 8.4,
        genres: ["Romance", "Drama", "Sobrenatural"],
        description: "Dois estranhos trocam de corpo e buscam um ao outro.",
        fullDescription: "Mitsuha e Taki são dois estranhos que vivem vidas totalmente diferentes. Mas quando Mitsuha começa a sonhar que é um garoto que vive em Tóquio, e Taki sonha que é uma garota que vive em uma cidade rural, eles percebem que algo misterioso está acontecendo.",
        episodes: 1,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/3KR8_igDs1Y"
    },
    {
        id: 13,
        name: "Horimiya",
        image: "https://media.kitsu.app/anime/poster_images/43545/large.jpg",
        rating: 8.1,
        genres: ["Romance", "Drama", "Escolar", "Slice of Life"],
        description: "Dois opostos se atraem e mostram seus verdadeiros eus.",
        fullDescription: "Embora admirada na escola por sua bondade e habilidade acadêmica, a estudante Kyoko Hori esconde outro lado de si mesma. Com os pais muitas vezes fora de casa a trabalho, Hori tem que cuidar de seu irmão mais novo e fazer o trabalho doméstico.",
        episodes: 13,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/6u_6-Vv67No"
    },
    {
        id: 14,
        name: "Re:Zero",
        image: "https://media.kitsu.app/anime/poster_images/11209/large.jpg",
        rating: 8.1,
        genres: ["Isekai", "Drama", "Terror", "Fantasia"],
        description: "Subaru morre e volta no tempo para salvar seus amigos.",
        fullDescription: "Subaru Natsuki é transportado para um mundo de fantasia. Lá, ele descobre que tem a habilidade de voltar no tempo toda vez que morre.",
        episodes: 50,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/Slz_V0G_u_M"
    },
    {
        id: 15,
        name: "Sword Art Online",
        image: "https://media.kitsu.app/anime/poster_images/6589/large.jpg",
        rating: 7.5,
        genres: ["Isekai", "Ação", "Fantasia"],
        description: "Jogadores presos em um MMORPG onde morrer no jogo é real.",
        fullDescription: "Em 2022, milhares de pessoas ficam presas em um MMORPG de realidade virtual, onde a única maneira de escapar é vencer o jogo, mas morrer no jogo significa morrer no mundo real.",
        episodes: 96,
        seasons: 4,
        trailer: "https://www.youtube.com/embed/6og_vWq8n60"
    },
    {
        id: 16,
        name: "Bleach",
        image: "https://media.kitsu.app/anime/poster_images/244/large.jpg",
        rating: 8.2,
        genres: ["Ação", "Shounen", "Sobrenatural"],
        description: "Ichigo Kurosaki se torna um Ceifador de Almas.",
        fullDescription: "Ichigo Kurosaki é um adolescente que pode ver fantasmas. Sua vida muda quando ele se torna um Soul Reaper para proteger os inocentes de espíritos malignos conhecidos como Hollows.",
        episodes: 366,
        seasons: 16,
        trailer: "https://www.youtube.com/embed/e8G_Y_5y-74"
    },
    {
        id: 17,
        name: "Dragon Ball Z",
        image: "https://media.kitsu.app/anime/720/poster_image/large-5cfc7e2756852e708c822df0a9f59871.jpeg",
        rating: 8.8,
        genres: ["Ação", "Shounen", "Aventura"],
        description: "Goku defende a Terra contra ameaças intergalácticas.",
        fullDescription: "Goku, o guerreiro mais forte do mundo, deve proteger a Terra de vilões poderosos, incluindo alienígenas, androides e monstros mágicos.",
        episodes: 291,
        seasons: 9,
        trailer: "https://www.youtube.com/embed/m9_5S38-I0Q"
    },
    {
        id: 18,
        name: "Vinland Saga",
        image: "https://media.kitsu.app/anime/poster_images/41084/large.jpg",
        rating: 8.8,
        genres: ["Ação", "Drama", "Seinen", "Histórico"],
        description: "Um jovem viking busca vingança em um mundo de guerra.",
        fullDescription: "Thorfinn é um jovem que cresceu ouvindo histórias sobre a lendária Vinland. Após a morte de seu pai pelas mãos de um mercenário, ele se junta ao grupo do assassino para buscar vingança.",
        episodes: 48,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/f8H2_ZpSAn0"
    },
    {
        id: 19,
        name: "Fullmetal Alchemist: Brotherhood",
        image: "https://media.kitsu.app/anime/poster_images/3936/large.jpg",
        rating: 9.1,
        genres: ["Ação", "Drama", "Aventura", "Shounen"],
        description: "Dois irmãos buscam a Pedra Filosofal.",
        fullDescription: "Dois irmãos usam a alquimia para tentar trazer sua mãe de volta à vida, mas o experimento falha tragicamente, e eles partem em uma jornada para recuperar seus corpos.",
        episodes: 64,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/B07_Dq_l6q8"
    },
    {
        id: 20,
        name: "Hunter x Hunter",
        image: "https://media.kitsu.app/anime/poster_images/6448/large.jpg",
        rating: 9.0,
        genres: ["Ação", "Aventura", "Shounen", "Fantasia"],
        description: "Gon busca seu pai e se torna um Hunter.",
        fullDescription: "Gon Freecss é um jovem que descobre que seu pai, que ele acreditava estar morto, é na verdade um Hunter lendário. Gon decide seguir os passos de seu pai e se tornar um Hunter também.",
        episodes: 148,
        seasons: 6,
        trailer: "https://www.youtube.com/embed/d6kBeJjGVnY"
    },
    {
        id: 21,
        name: "Cyberpunk: Edgerunners",
        image: "https://media.kitsu.app/anime/43248/poster_image/large-a9fe312b804fd8067d13c5ca4bef3ae6.jpeg",
        rating: 8.3,
        genres: ["Ação", "Drama", "Sci-Fi", "Seinen"],
        description: "Um jovem tenta sobreviver em uma cidade obcecada por tecnologia.",
        fullDescription: "Em uma distopia futurista, um jovem de rua talentoso, mas imprudente, tenta sobreviver em uma cidade obcecada pela tecnologia e modificação corporal.",
        episodes: 10,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/OiR_lS0S634"
    },
    {
        id: 22,
        name: "Steins;Gate",
        image: "https://media.kitsu.app/anime/poster_images/5646/large.jpg",
        rating: 9.1,
        genres: ["Sci-Fi", "Thriller", "Psicológico", "Drama"],
        description: "Um grupo de amigos descobre como enviar mensagens ao passado.",
        fullDescription: "Um cientista excêntrico e seus amigos descobrem acidentalmente uma maneira de enviar mensagens de texto para o passado, desencadeando uma série de eventos perigosos.",
        episodes: 24,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/27OZc-ku6is"
    },
    {
        id: 23,
        name: "Haikyuu!!",
        image: "https://media.kitsu.app/anime/poster_images/8133/large.jpg",
        rating: 8.7,
        genres: ["Esporte", "Comédia", "Shounen", "Escolar"],
        description: "Shoyo Hinata quer ser o melhor jogador de vôlei.",
        fullDescription: "Inspirado por um jogador de vôlei apelidado de 'Pequeno Gigante', Shoyo Hinata decide criar seu próprio time de vôlei e competir no ensino médio.",
        episodes: 85,
        seasons: 4,
        trailer: "https://www.youtube.com/embed/JOGp2c7-cKc"
    },
    {
        id: 24,
        name: "My Hero Academia",
        image: "https://media.kitsu.app/anime/poster_images/11469/large.jpg",
        rating: 7.9,
        genres: ["Ação", "Shounen", "Escolar"],
        description: "Um garoto sem poderes entra na melhor escola de heróis.",
        fullDescription: "Em um mundo onde a maioria da população possui superpoderes, Izuku Midoriya nasce sem eles, mas ainda sonha em se tornar um herói.",
        episodes: 138,
        seasons: 6,
        trailer: "https://www.youtube.com/embed/D5fyC6_p7Ps"
    },
    {
        id: 25,
        name: "One Punch Man",
        image: "https://media.kitsu.app/anime/poster_images/10740/large.jpg",
        rating: 8.7,
        genres: ["Ação", "Comédia", "Seinen", "Sci-Fi"],
        description: "Saitama é um herói que derrota qualquer um com um soco.",
        fullDescription: "Saitama é um herói tão poderoso que derrota todos os seus oponentes com apenas um soco, o que o leva a se sentir entediado e em busca de um desafio real.",
        episodes: 24,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/Poo5lqoWSGw"
    },
    {
        id: 26,
        name: "Mob Psycho 100",
        image: "https://media.kitsu.app/anime/11578/poster_image/large-e969f8a688549dd8e02ffd59f49122e9.jpeg",
        rating: 8.6,
        genres: ["Ação", "Comédia", "Sobrenatural", "Shounen"],
        description: "Um garoto com poderes psíquicos tenta viver uma vida normal.",
        fullDescription: "Mob é um jovem com habilidades psíquicas incríveis, mas ele prefere viver uma vida normal e manter seus poderes sob controle.",
        episodes: 37,
        seasons: 3,
        trailer: "https://www.youtube.com/embed/0S93VvshR9Y"
    },
    {
        id: 27,
        name: "Kaguya-sama: Love is War",
        image: "https://media.kitsu.app/anime/poster_images/41373/large.jpg",
        rating: 8.5,
        genres: ["Romance", "Comédia", "Escolar", "Seinen"],
        description: "Dois gênios tentam fazer o outro confessar seu amor primeiro.",
        fullDescription: "Kaguya Shinomiya e Miyuki Shirogane são dois estudantes brilhantes que se gostam, mas seu orgulho os impede de confessar seus sentimentos.",
        episodes: 37,
        seasons: 3,
        trailer: "https://www.youtube.com/embed/2_YI6S_vW_0"
    },
    {
        id: 28,
        name: "Code Geass",
        image: "https://media.kitsu.app/anime/poster_images/1415/large.jpg",
        rating: 8.7,
        genres: ["Ação", "Drama", "Sci-Fi", "Mecha", "Psicológico"],
        description: "Um príncipe exilado usa o poder do Geass para derrubar um império.",
        fullDescription: "Lelouch Lamperouge, um príncipe exilado, obtém o poder do Geass e decide usá-lo para destruir o Império Britânico sagrado.",
        episodes: 50,
        seasons: 2,
        trailer: "https://www.youtube.com/embed/O8S88K_AAnM"
    },
    {
        id: 29,
        name: "Cowboy Bebop",
        image: "https://media.kitsu.app/anime/poster_images/1/large.jpg",
        rating: 8.9,
        genres: ["Ação", "Sci-Fi", "Aventura", "Seinen"],
        description: "Caçadores de recompensas viajam pelo espaço em busca de criminosos.",
        fullDescription: "Spike Spiegel e seu grupo de caçadores de recompensas viajam pelo espaço em sua nave, a Bebop, em busca de criminosos perigosos.",
        episodes: 26,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/qSHeXvY_v2M"
    },
    {
        id: 30,
        name: "Neon Genesis Evangelion",
        image: "https://media.kitsu.app/anime/21/poster_image/large-9a3a9086a1b563e9e72d510118eb7d3c.jpeg",
        rating: 8.5,
        genres: ["Sci-Fi", "Drama", "Mecha", "Psicológico"],
        description: "Pilotos de robôs gigantes defendem a humanidade contra anjos.",
        fullDescription: "Em um futuro pós-apocalíptico, a humanidade deve lutar contra seres misteriosos conhecidos como Anjos usando robôs gigantes chamados Evangelions.",
        episodes: 26,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/jYZfeY8Vg0E"
    },
    {
        id: 31,
        name: "Monster",
        image: "https://media.kitsu.app/anime/poster_images/1110/large.jpg",
        rating: 9.1,
        genres: ["Mistério", "Thriller", "Psicológico", "Seinen", "Drama"],
        description: "Um médico busca um assassino que ele salvou no passado.",
        fullDescription: "Kenzou Tenma, um neurocirurgião japonês de elite que trabalha na Alemanha, vê sua vida virar de cabeça para baixo depois de se envolver com um ex-paciente que se revela um assassino em série psicopata.",
        episodes: 74,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/1lyVwXv9C6s"
    },
    {
        id: 32,
        name: "Fruits Basket (2019)",
        image: "https://media.kitsu.app/anime/poster_images/41804/large.jpg",
        rating: 8.6,
        genres: ["Romance", "Drama", "Shoujo", "Sobrenatural", "Slice of Life"],
        description: "Tooru Honda mora com a misteriosa família Souma.",
        fullDescription: "Depois que uma tragédia familiar vira sua vida de cabeça para baixo, a estudante do ensino médio Tohru Honda decide cuidar das coisas por conta própria e se muda para... uma barraca! Infelizmente para ela, sua nova casa fica em terras privadas pertencentes ao misterioso clã Sohma.",
        episodes: 63,
        seasons: 3,
        trailer: "https://www.youtube.com/embed/K8_YI8I9Z70"
    },
    {
        id: 33,
        name: "Clannad: After Story",
        image: "https://media.kitsu.app/anime/poster_images/3432/large.jpg",
        rating: 8.9,
        genres: ["Drama", "Romance", "Slice of Life", "Sobrenatural"],
        description: "A vida de Tomoya e Nagisa após o ensino médio.",
        fullDescription: "A continuação da série Clannad, seguindo a vida de Tomoya Okazaki e Nagisa Furukawa enquanto eles enfrentam os desafios da vida adulta e da família.",
        episodes: 24,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/v_7yTlhSAnY"
    },
    {
        id: 34,
        name: "Bocchi the Rock!",
        image: "https://media.kitsu.app/anime/44372/poster_image/large-220054817da3d95f448d390233b664d0.jpeg",
        rating: 8.6,
        genres: ["Comédia", "Slice of Life", "Música", "Escolar"],
        description: "Uma garota ansiosa entra em uma banda de rock.",
        fullDescription: "Hitori Gotou é uma estudante do ensino médio que começa a aprender a tocar violão porque sonha em estar em uma banda, mas ela é tão tímida que não fez um único amigo. No entanto, seu sonho pode se tornar realidade depois que ela conhece Nijika Ijichi.",
        episodes: 12,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/5U7Z0sYvA2Y"
    },
    {
        id: 35,
        name: "Frieren: Beyond Journey's End",
        image: "https://media.kitsu.app/anime/46387/poster_image/large-f236058e17b8f95c4794834da99b2446.jpeg",
        rating: 9.1,
        genres: ["Aventura", "Fantasia", "Drama", "Shounen"],
        description: "Uma maga elfa reflete sobre a vida e a mortalidade.",
        fullDescription: "A maga elfa Frieren e seus corajosos companheiros aventureiros derrotaram o Rei Demônio e trouxeram a paz à terra. Mas Frieren sobreviverá muito mais que o resto de seu antigo grupo. Como ela entenderá o que a vida significa para as pessoas ao seu redor?",
        episodes: 28,
        seasons: 1,
        trailer: "https://www.youtube.com/embed/qSHeXvY_v2M"
    }
];
